trigger:
  branches:
    include: [ '*' ]
    exclude: [ gh-pages, master, canary_base ]
  paths:
    exclude:
    - '*.md'
    - '.appveyor.yml'
    - '.github/**'
    - 'docs/**'
    - 'LICENSE'
pr:
  branches:
    include: [ '*' ]
    exclude: [ gh-pages, master, canary_base ]
  paths:
    exclude:
    - '*.md'
    - '.appveyor.yml'
    - '.github/**'
    - 'docs/**'
    - 'LICENSE'

pool:
  vmImage: windows-latest
variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1
steps:
- pwsh: .\xb setup
  displayName: Setup
- pwsh: .\xb build --target=src\xenia-app --target=src\xenia-vfs-dump
  displayName: Build
- pwsh: |-
    robocopy . build\bin\Windows\Release                                                                                               LICENSE /r:0 /w:0
    robocopy   build\bin\Windows\Release $(Build.ArtifactStagingDirectory)\xenia_canary          xenia_canary.exe   xenia_canary.pdb   LICENSE /r:0 /w:0
    robocopy   build\bin\Windows\Release $(Build.ArtifactStagingDirectory)\xenia-vfs-dump_canary xenia-vfs-dump.exe xenia-vfs-dump.pdb LICENSE /r:0 /w:0
    If ($LastExitCode -le 7) { echo "LastExitCode = $LastExitCode";$LastExitCode = 0 }
  displayName: Prepare artifacts
- publish: $(Build.ArtifactStagingDirectory)\xenia_canary
  artifact: xenia_canary
  displayName: Publish xenia_canary artifacts
- publish: $(Build.ArtifactStagingDirectory)\xenia-vfs-dump_canary
  artifact: xenia-vfs-dump_canary
  displayName: Publish xenia-vfs-dump_canary artifacts
